### PR TITLE
Added dadjoke command since ADU had it in the to-do list

### PR DESCRIPTION
**Pull request by KowlinMC**
Why not ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by TheEquity** [comment]
I am sure a discord user would notice this, but your way of doing this is really bad considering the `requests` module being blocking which could crash the bot if too many people are using or spamming this. An alternative is to use `aiohttp`.

Example of usage:
```python
import aiohttp
import asyncio

async def main():
    async with aiohttp.ClientSession() as a:
         resp = await a.get("https://notequity.com/stats")
         json = await resp.json()
         print(json)
         

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Comment by KowlinMC** [comment]
> I am sure a discord user would notice this, but your way of doing this is really bad considering the `requests` module being blocking which could crash the bot if too many people are using or spamming this. An alternative is to use `aiohttp`.
> 
> Example of usage:
> 
> ```python
> import aiohttp
> import asyncio
> 
> async def main():
>     async with aiohttp.ClientSession() as a:
>          resp = await a.get("https://notequity.com/stats")
>          json = await resp.json()
>          print(json)
>          
> 
> loop = asyncio.get_event_loop()
> loop.run_until_complete(main())
> ```

hmmm, it's the way i've always used it and there hasn't ever been an issue

**Comment by KowlinMC** [comment]
Whoops, accidentally closed it.

**Comment by TheEquity** [comment]
btw im too lazy to edit your pr anyways

**Pull request closed without merging**
